version: '3'
services:
  api:
    build: ./api
    ports:
      - ${API_PORT}:${API_PORT}
    volumes:
      - ./api/src:/app/src  
    command: ["yarn", "start"]
    environment:
      SERVER_NAME: ${SERVER_NAME}
      API_PORT: ${API_PORT}
      NODE_ENV: ${APP_ENV}
 