version: "3"
services:
  api:
    container_name: garage_api
    build:
      context: .
      dockerfile: api.Dockerfile
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
      - 9229:9229
    volumes:
      - ./api/src:/app/src
      - ./config:/app/src/config
      - ./models:/app/src/models
      - ./migrations:/app/migrations
      - ./seeders:/app/seeders
    command: ["yarn", "start"]
    environment:
      SERVER_NAME: ${SERVER_NAME}
      API_PORT: ${API_PORT}
      NODE_ENV: ${APP_ENV}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_DATABASE: ${POSTGRES_DB}

  db:
    restart: on-failure
    image: postgres:10-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ./data/postgres-${APP_ENV}:/var/lib/postgresql/data
